apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "willer"
  description: "try using template for willer"
  annotations:
    github.com/project-slug: lab49-poc/willer
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - springboot
    - kubernetes
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: "team-a"
  providesApis:
    - willer
  consumesApis:
    - petstore
